name: Node.js Package

on:
  push:
    branches:
      - main
      - test
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc --showConfig # Debug TypeScript configuration
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Check if version exists and publish
        id: version-check
        run: |
          current_version=$(npm pkg get version | tr -d '"')
          echo "Current version: $current_version"
          
          # Check if the version has already been bumped in a previous run
          tag_exists=$(git tag -l "$current_version")

          # If the version already exists, bump it and check again
          while [ -n "$tag_exists" ]; do
            echo "Version $current_version already exists. Bumping version."
            npm version patch -m "Bumped to version %s"
            current_version=$(npm pkg get version | tr -d '"')
            tag_exists=$(git tag -l "$current_version")
          done

          echo "Using version $current_version"
          echo "version=$current_version" >> $GITHUB_ENV
      - name: Check and Bump Version
        run: |
          current_version=$(npm pkg get version | tr -d '"')
          echo "Current version: $current_version"
      
          # Check if the version needs to be bumped
          if [ "$current_version" != "${{ env.version }}" ]; then
            echo "Version $current_version does not match. Bumping to version ${{ env.version }}."
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            npm version ${{ env.version }}
            git push
          else
            echo "Version is already at $current_version. No bump needed."
          fi
      - name: Publish Package
        run: |
          echo "Publishing version ${{ env.version }}"
          if [ "${{ github.ref_name }}" == "test" ]; then
            npm publish --tag test
          elif [ "${{ github.ref_name }}" == "development" ]; then
            npm publish --tag development
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
