name: Node.js Package

on:
  push:
    branches:
      - main
      - test
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc --showConfig # Debug TypeScript configuration
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Publish Package
        run: |
          if [ "${{ github.ref_name }}" == "test" ]; then
            npm publish --tag test
          elif [ "${{ github.ref_name }}" == "development" ]; then
            npm publish --tag development
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
