name: Node.js Package

on:
  # push:
  #   branches:
  #     - main
  #     - test
  #     - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc --showConfig # Debug TypeScript configuration
      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - name: Check if version exists and publish
        id: version-check
        run: |
          current_version=$(npm pkg get version | tr -d '"')
          echo "Current version: $current_version"
          
          # Initialize current_version and tag_exists
          git fetch --tags
          
          # If the version already exists, bump it and check again
          while [ -n "$(git tag -l "$current_version")" ]; do
              echo "Tag For Version $current_version already exists. Bumping version."
              npm version patch --no-git-tag-version
              current_version=$(npm pkg get version | tr -d '"')
          done
          
          git fetch origin
          git reset --hard
            
          echo "Next available version is $current_version."
          echo "version=$current_version" >> $GITHUB_ENV
      - name: Check and Bump Version
        run: |
          current_version=$(npm pkg get version | tr -d '"')
          echo "Current version: $current_version"
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
          # Check if the version needs to be bumped
          if [ "$current_version" != "${{ env.version }}" ]; then
            echo "Version $current_version does not match. Bumping to version ${{ env.version }}."
            npm version ${{ env.version }}
            git push
          else
            echo "Version is already at $current_version. No bump needed."
            git tag "$current_version"
            git push origin "$current_version"
          fi
      - name: Publish Package
        run: |
          echo "Publishing version ${{ env.version }}"
          if [ "${{ github.ref_name }}" == "test" ]; then
            npm publish --tag test
          elif [ "${{ github.ref_name }}" == "development" ]; then
            npm publish --tag development
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
